$(document).ready(function(){
    $("#message-um").click(function(){
        $(".chat-messages").hide();
        $(".chats").show();
    });
    $(".msg-back").click(function(){
        $(".chat-messages").show();
        $(".chats").hide();
    });
    $("#story-um").click(function(){
        $(".menu").hide();
        $(".see-more").hide();
        $(".full-story").show();
    });
    $(".full-story").click(function(){
        $(".menu").show();
        $(".see-more").show();
        $(".full-story").hide();
    });
    $("#discovery-dois").click(function(){
        $(".menu").hide();
        $(".see-more").hide();
        $(".full-discovery").show();
    });
    $(".full-discovery").click(function(){
        $(".menu").show();
        $(".see-more").show();
        $(".full-discovery").hide();
    });
    $("#next").click(function(){
        $("#next").hide();
        $("input[type='password']").hide();
        $("#policy").show();
        $("#login").attr("style", "display: block");
    });
});